default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Capstone_Felicia_Wong_development
#  timeout: 5000

# test:
#   <<: *default
#   database: Capstone_Felicia_Wong_test
#
# production:
#   <<: *default
#   database: Capstone_Felicia_Wong_production
#   username: Capstone_Felicia_Wong
#   password: <%= ENV['CAPSTONE_FELICIA_WONG_DATABASE_PASSWORD'] %>
