# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d3197fe20662c1876ef289abb7217beb9a7c3a03df52683f6442c5300f92991d06eeb5fb5f3e7473a25367940614d111e3f512944a238bcdee277fcc98b03a

test:
  secret_key_base: d0763c05fe3848cc92d891e1b4526e83bf8fefa7c9eed848e891c3b82a619fbc940e8a8f3e13ef2edc52697a818a536ad6b92e8c897ce3ae8e1ddb3dac6c73c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
